In [2]:
dataFrame = pd.read_csv('C:/Users/Pro/Desktop/kidney.csv')
df = dataFrame.copy()

In [3]:
df

id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present   
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent   
..   ...   ...   ...    ...  ...  ...     ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no   
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no   
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes   
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes   
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no   
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no   
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no   
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no   
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no   
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[400 rows x 26 columns]

In [4]:
df['sg']

0      1.020
1      1.020
2      1.010
3      1.005
4      1.010
       ...  
395    1.020
396    1.025
397    1.020
398    1.025
399    1.025
Name: sg, Length: 400, dtype: float64

In [5]:
df.isnull().any()

id                False
age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [6]:
df.describe()

id         age          bp          sg          al          su  \
count  400.000000  391.000000  388.000000  353.000000  354.000000  351.000000   
mean   199.500000   51.483376   76.469072    1.017408    1.016949    0.450142   
std    115.614301   17.169714   13.683637    0.005717    1.352679    1.099191   
min      0.000000    2.000000   50.000000    1.005000    0.000000    0.000000   
25%     99.750000   42.000000   70.000000    1.010000    0.000000    0.000000   
50%    199.500000   55.000000   80.000000    1.020000    0.000000    0.000000   
75%    299.250000   64.500000   80.000000    1.020000    2.000000    0.000000   
max    399.000000   90.000000  180.000000    1.025000    5.000000    5.000000   

              bgr          bu          sc         sod         pot        hemo  
count  356.000000  381.000000  383.000000  313.000000  312.000000  348.000000  
mean   148.036517   57.425722    3.072454  137.528754    4.627244   12.526437  
std     79.281714   50.503006    5.741126   10.408752    3.193904    2.912587  
min     22.000000    1.500000    0.400000    4.500000    2.500000    3.100000  
25%     99.000000   27.000000    0.900000  135.000000    3.800000   10.300000  
50%    121.000000   42.000000    1.300000  138.000000    4.400000   12.650000  
75%    163.000000   66.000000    2.800000  142.000000    4.900000   15.000000  
max    490.000000  391.000000   76.000000  163.000000   47.000000   17.800000

In [7]:
df.dtypes

id                  int64
age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                object
pc                 object
pcc                object
ba                 object
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv                object
wc                 object
rc                 object
htn                object
dm                 object
cad                object
appet              object
pe                 object
ane                object
classification     object
dtype: object

In [8]:
#number of null values in age 
df['age'].isna().sum()
#continuous values so we replaced it with mean 
age_average_value = df['age'].mean()
df['age'].replace(np.nan, age_average_value, inplace = True)
df['age'].unique()

array([48.        ,  7.        , 62.        , 51.        , 60.        ,
       68.        , 24.        , 52.        , 53.        , 50.        ,
       63.        , 40.        , 47.        , 61.        , 21.        ,
       42.        , 75.        , 69.        , 51.48337596, 73.        ,
       70.        , 65.        , 76.        , 72.        , 82.        ,
       46.        , 45.        , 35.        , 54.        , 11.        ,
       59.        , 67.        , 15.        , 55.        , 44.        ,
       26.        , 64.        , 56.        ,  5.        , 74.        ,
       38.        , 58.        , 71.        , 34.        , 17.        ,
       12.        , 43.        , 41.        , 57.        ,  8.        ,
       39.        , 66.        , 81.        , 14.        , 27.        ,
       83.        , 30.        ,  4.        ,  3.        ,  6.        ,
       32.        , 80.        , 49.        , 90.        , 78.        ,
       19.        ,  2.        , 33.        , 36.        , 37.  

In [9]:
df['bp'].isna().sum()
#continuous values so we replaced it with mean 
bp_average_value = df['bp'].mean()
df['bp'].replace(np.nan, bp_average_value, inplace = True)

df['bp'].unique()

array([ 80.        ,  50.        ,  70.        ,  90.        ,
        76.46907216, 100.        ,  60.        , 110.        ,
       140.        , 180.        , 120.        ])

In [10]:
df['sg'].isna().sum()

#discrete values so we replaced with most frequent
sg_frequent_value = df['sg'].value_counts().idxmax()
df['sg'].replace(np.nan, sg_frequent_value, inplace = True )

df['sg'].unique()

array([1.02 , 1.01 , 1.005, 1.015, 1.025])

In [11]:
df['al'].isna().sum()
#discrete values so we replaced with most frequent
al_frequent_value = df['al'].value_counts().idxmax()
df['al'].replace(np.nan, al_frequent_value, inplace = True)

df['al'].unique()

array([1., 4., 2., 3., 0., 5.])

In [12]:
df['su'].isna().sum()
df['su'].value_counts()
#discrete values so we replaced with most frequent
su_frequent_value = df['su'].value_counts().idxmax()
df['su'].replace(np.nan, su_frequent_value, inplace = True)
df['su'].unique()

array([0., 3., 4., 1., 2., 5.])

In [13]:
df['rbc'].isna().sum()
#discrete values so we replaced with most frequent
rbc_frequent_value = df['rbc'].value_counts().idxmax()
df['rbc'].replace(np.nan, rbc_frequent_value, inplace = True)
#encoding and processing the values
df['rbc'].replace('normal', 1, inplace = True)
df['rbc'].replace('abnormal', 0, inplace = True)
df['rbc'].unique()

array([1, 0], dtype=int64)

In [14]:
df['pc'].isna().sum()
#discrete values so we replaced with most frequent
pc_frequent_value = df['pc'].value_counts().idxmax()
df['pc'].replace(np.nan, pc_frequent_value, inplace = True)
#encoding and processing the values
df['pc'].replace('normal', 1, inplace = True)
df['pc'].replace('abnormal', 0, inplace = True)
df['pc'].unique()

array([1, 0], dtype=int64)

In [15]:
df['pcc'].isna().sum()
#discrete values so we replaced with most frequent
pcc_frequent_value = df['pcc'].value_counts().idxmax()
df['pcc'].replace(np.nan, pcc_frequent_value, inplace = True )
#encoding and processing the values
df['pcc'].replace('no', 'notpresent', inplace = True)
df['pcc'].replace('notpresent', 0, inplace = True)
df['pcc'].replace('present', 1, inplace = True)
df['pcc'].unique()

array([0, 1], dtype=int64)

In [16]:
df['ba'].isna().sum()
#discrete values so we replaced with most frequent
ba_frequent_value = df['ba'].value_counts().idxmax()
df['ba'].replace(np.nan, ba_frequent_value, inplace = True )
#encoding and processing the values
df['ba'].replace('notpresent', 0, inplace = True)
df['ba'].replace('present', 1, inplace = True)
df['ba'].unique()

array([0, 1], dtype=int64)

In [63]:
df['bgr'].isna().sum()
#continuous values so we replaced with mean 
bgr_average_value = df['bgr'].mean()
df['bgr'].replace(np.nan, bgr_average_value, inplace = True )

df['bgr'].unique()


array([121.        , 148.03651685, 423.        , 117.        ,
       106.        ,  74.        , 100.        , 410.        ,
       138.        ,  70.        , 490.        , 380.        ,
       208.        ,  98.        , 157.        ,  76.        ,
        99.        , 114.        , 263.        , 173.        ,
        95.        , 108.        , 156.        , 264.        ,
       123.        ,  93.        , 107.        , 159.        ,
       140.        , 171.        , 270.        ,  92.        ,
       137.        , 204.        ,  79.        , 207.        ,
       124.        , 144.        ,  91.        , 162.        ,
       246.        , 253.        , 141.        , 182.        ,
        86.        , 150.        , 146.        , 425.        ,
       112.        , 250.        , 360.        , 163.        ,
       129.        , 133.        , 102.        , 158.        ,
       165.        , 132.        , 104.        , 127.        ,
       415.        , 169.        , 251.        , 109.  

In [66]:
df['bu'].isna().sum()
#continuous values so we replaced it with mean 
bu_average_value =  df['bu'].mean()
df['bu'].replace(np.nan, bu_average_value, inplace = True )

df['bu'].unique()

array([ 36.        ,  18.        ,  53.        ,  56.        ,
        26.        ,  25.        ,  54.        ,  31.        ,
        60.        , 107.        ,  55.        ,  72.        ,
        86.        ,  90.        , 162.        ,  46.        ,
        87.        ,  27.        , 148.        , 180.        ,
       163.        ,  57.42572178,  50.        ,  75.        ,
        45.        ,  28.        , 155.        ,  33.        ,
        39.        , 153.        ,  29.        ,  65.        ,
       103.        ,  70.        ,  80.        ,  20.        ,
       202.        ,  77.        ,  89.        ,  24.        ,
        17.        ,  32.        , 114.        ,  66.        ,
        38.        , 164.        , 142.        ,  96.        ,
       391.        ,  15.        , 111.        ,  73.        ,
        19.        ,  92.        ,  35.        ,  16.        ,
       139.        ,  48.        ,  85.        ,  98.        ,
       186.        ,  37.        ,  47.        ,  52.  

In [70]:
df['sc'].isna().sum()
#continuous values so we replaced it with mean 
sc_average_value =  df['sc'].mean()
df['sc'].replace(np.nan, sc_average_value, inplace = True )

df['sc'].unique()


array([ 1.2       ,  0.8       ,  1.8       ,  3.8       ,  1.4       ,
        1.1       , 24.        ,  1.9       ,  7.2       ,  4.        ,
        2.7       ,  2.1       ,  4.6       ,  4.1       ,  9.6       ,
        2.2       ,  5.2       ,  1.3       ,  1.6       ,  3.9       ,
       76.        ,  7.7       ,  3.07245431,  2.4       ,  7.3       ,
        1.5       ,  2.5       ,  2.        ,  3.4       ,  0.7       ,
        1.        , 10.8       ,  6.3       ,  5.9       ,  0.9       ,
        3.        ,  3.25      ,  9.7       ,  6.4       ,  3.2       ,
       32.        ,  0.6       ,  6.1       ,  3.3       ,  6.7       ,
        8.5       ,  2.8       , 15.        ,  2.9       ,  1.7       ,
        3.6       ,  5.6       ,  6.5       ,  4.4       , 10.2       ,
       11.5       ,  0.5       , 12.2       ,  5.3       ,  9.2       ,
       13.8       , 16.9       ,  6.        ,  7.1       , 18.        ,
        2.3       , 13.        , 48.1       , 14.2       , 16.4 

In [72]:
df['sod'].isna().sum()
#continuous values so we replaced it with mean 
sod_average_value =  df['sod'].mean()
df['sod'].replace(np.nan, sod_average_value, inplace = True )

df['sod'].unique()


163.0

In [75]:
df['pot'].isna().sum()
#continuous values so we replaced it with mean 
pot_average_value =  df['pot'].mean()
df['pot'].replace(np.nan, pot_average_value, inplace = True )

df['pot'].unique()


array([ 4.62724359,  2.5       ,  3.2       ,  4.        ,  3.7       ,
        4.2       ,  5.8       ,  3.4       ,  6.4       ,  4.9       ,
        4.1       ,  4.3       ,  5.2       ,  3.8       ,  4.6       ,
        3.9       ,  4.7       ,  5.9       ,  4.8       ,  4.4       ,
        6.6       , 39.        ,  5.5       ,  5.        ,  3.5       ,
        3.6       ,  7.6       ,  2.9       ,  4.5       ,  5.7       ,
        5.4       ,  5.3       , 47.        ,  6.3       ,  5.1       ,
        5.6       ,  3.        ,  2.8       ,  2.7       ,  6.5       ,
        3.3       ])

In [78]:
df['hemo'].isna().sum()
#continuous values so we replaced it with mean 
hemo_average_value =  df['hemo'].mean()
df['hemo'].replace(np.nan, hemo_average_value, inplace = True )

df['hemo'].unique()


array([15.4       , 11.3       ,  9.6       , 11.2       , 11.6       ,
       12.2       , 12.4       , 10.8       ,  9.5       ,  9.4       ,
        9.7       ,  9.8       ,  5.6       ,  7.6       , 12.6       ,
       12.1       , 12.7       , 10.3       ,  7.7       , 10.9       ,
       12.52643678, 11.1       ,  9.9       , 12.5       , 12.9       ,
       10.1       , 12.        , 13.        ,  7.9       ,  9.3       ,
       15.        , 10.        ,  8.6       , 13.6       , 10.2       ,
       10.5       ,  6.6       , 11.        ,  7.5       , 15.6       ,
       15.2       ,  4.8       ,  9.1       ,  8.1       , 11.9       ,
       13.5       ,  8.3       ,  7.1       , 16.1       , 10.4       ,
        9.2       ,  6.2       , 13.9       , 14.1       ,  6.        ,
       11.8       , 11.7       , 11.4       , 14.        ,  8.2       ,
       13.2       ,  6.1       ,  8.        , 12.3       ,  8.4       ,
       14.3       ,  9.        ,  8.7       , 10.6       , 13.1 

In [81]:
df['pcv'].isna().sum()
#cleaning the noise in the data
df['pcv'].replace('\t?', np.nan, inplace = True )
df['pcv'].replace('\t43', 43, inplace = True )
df['pcv'] = df['pcv'].astype('float')
#continuous values so we replaced it with mean 
pcv_average_value =  df['pcv'].mean()
df['pcv'].replace(np.nan, pcv_average_value, inplace = True )

df['pcv'].unique()


array([44.        , 38.        , 31.        , 32.        , 35.        ,
       39.        , 36.        , 33.        , 29.        , 28.        ,
       38.88449848, 16.        , 24.        , 37.        , 30.        ,
       34.        , 40.        , 45.        , 27.        , 48.        ,
       52.        , 14.        , 22.        , 18.        , 42.        ,
       17.        , 46.        , 23.        , 19.        , 25.        ,
       41.        , 26.        , 15.        , 21.        , 43.        ,
       20.        , 47.        ,  9.        , 49.        , 50.        ,
       53.        , 51.        , 54.        ])

In [84]:
df['wc'].isna().sum()
#cleaning the noise in the data
df['wc'].replace('\t6200', 6200, inplace = True )
df['wc'].replace('\t6200', 6200, inplace = True )
df['wc'].replace('\t?', np.nan, inplace = True )
df['wc'] = df['wc'].astype('float')
#continuous values so we replaced it with mean 
wc_average_value =  df['wc'].mean()
df['wc'].replace(np.nan, wc_average_value, inplace = True )

df['wc'].unique()


array([ 7800.        ,  6000.        ,  7500.        ,  6700.        ,
        7300.        ,  8406.12244898,  6900.        ,  9600.        ,
       12100.        ,  4500.        , 12200.        , 11000.        ,
        3800.        , 11400.        ,  5300.        ,  9200.        ,
        6200.        ,  8300.        ,  8400.        , 10300.        ,
        9800.        ,  9100.        ,  7900.        ,  6400.        ,
        8600.        , 18900.        , 21600.        ,  4300.        ,
        8500.        , 11300.        ,  7200.        ,  7700.        ,
       14600.        ,  6300.        ,  7100.        , 11800.        ,
        9400.        ,  5500.        ,  5800.        , 13200.        ,
       12500.        ,  5600.        ,  7000.        , 11900.        ,
       10400.        , 10700.        , 12700.        ,  6800.        ,
        6500.        , 13600.        , 10200.        ,  9000.        ,
       14900.        ,  8200.        , 15200.        ,  5000.        ,
      

In [87]:
df['rc'].isna().sum()
#cleaning the noise in the data
df['rc'].replace('\t?', np.nan, inplace = True )
df['rc'] = df['rc'].astype('float')
#continuous values so we replaced it with mean 
rc_average_value =  df['rc'].mean()
df['rc'].replace(np.nan, rc_average_value, inplace = True )

df['rc'].unique()


array([5.2       , 4.70743494, 3.9       , 4.6       , 4.4       ,
       5.        , 4.        , 3.7       , 3.8       , 3.4       ,
       2.6       , 2.8       , 4.3       , 3.2       , 3.6       ,
       4.1       , 4.9       , 2.5       , 4.2       , 4.5       ,
       3.1       , 4.7       , 3.5       , 6.        , 2.1       ,
       5.6       , 2.3       , 2.9       , 2.7       , 8.        ,
       3.3       , 3.        , 2.4       , 4.8       , 5.4       ,
       6.1       , 6.2       , 6.3       , 5.1       , 5.8       ,
       5.5       , 5.3       , 6.4       , 5.7       , 5.9       ,
       6.5       ])

In [26]:
df

id   age    bp     sg   al   su  rbc  pc  pcc  ba  ...   pcv      wc  \
0      0  48.0  80.0  1.020  1.0  0.0    1   1    0   0  ...  44.0  7800.0   
1      1   7.0  50.0  1.020  4.0  0.0    1   1    0   0  ...  38.0  6000.0   
2      2  62.0  80.0  1.010  2.0  3.0    1   1    0   0  ...  31.0  7500.0   
3      3  48.0  70.0  1.005  4.0  0.0    1   0    1   0  ...  32.0  6700.0   
4      4  51.0  80.0  1.010  2.0  0.0    1   1    0   0  ...  35.0  7300.0   
..   ...   ...   ...    ...  ...  ...  ...  ..  ...  ..  ...   ...     ...   
395  395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  ...  47.0  6700.0   
396  396  42.0  70.0  1.025  0.0  0.0    1   1    0   0  ...  54.0  7800.0   
397  397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  ...  49.0  6600.0   
398  398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  ...  51.0  7200.0   
399  399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  ...  53.0  6800.0   

           rc  htn   dm  cad  appet   pe  ane classification  
0    5.200000  yes  yes   no   good   no   no            ckd  
1    4.707435   no   no   no   good   no   no            ckd  
2    4.707435   no  yes   no   poor   no  yes            ckd  
3    3.900000  yes   no   no   poor  yes  yes            ckd  
4    4.600000   no   no   no   good   no   no            ckd  
..        ...  ...  ...  ...    ...  ...  ...            ...  
395  4.900000   no   no   no   good   no   no         notckd  
396  6.200000   no   no   no   good   no   no         notckd  
397  5.400000   no   no   no   good   no   no         notckd  
398  5.900000   no   no   no   good   no   no         notckd  
399  6.100000   no   no   no   good   no   no         notckd  

[400 rows x 26 columns]

In [27]:
df['htn'].isna().sum()
#discrete values so we replaced with most frequent
htn_frequent_value = df['htn'].value_counts().idxmax()
df['htn'].replace(np.nan, htn_frequent_value, inplace = True )

#encoding and processing the values
df['htn'].replace('no', 0, inplace = True)
df['htn'].replace('yes', 1, inplace = True)
df['htn'].unique()


array([1, 0], dtype=int64)

In [28]:
df['dm'].isna().sum()
#cleaning the noise in the data
df['dm'].replace(' yes', 'yes', inplace = True )
df['dm'].replace('\tyes', 'yes', inplace = True )
df['dm'].replace('\tno', 'no', inplace = True )

#discrete values so we replaced with most frequent
dm_frequent_value = df['dm'].value_counts().idxmax()
df['dm'].replace(np.nan, dm_frequent_value, inplace = True )

#encoding and processing the values
df['dm'].replace('no', 0, inplace = True)
df['dm'].replace('yes', 1, inplace = True)

df['dm'].unique()

array([1, 0], dtype=int64)

In [29]:
df

id   age    bp     sg   al   su  rbc  pc  pcc  ba  ...   pcv      wc  \
0      0  48.0  80.0  1.020  1.0  0.0    1   1    0   0  ...  44.0  7800.0   
1      1   7.0  50.0  1.020  4.0  0.0    1   1    0   0  ...  38.0  6000.0   
2      2  62.0  80.0  1.010  2.0  3.0    1   1    0   0  ...  31.0  7500.0   
3      3  48.0  70.0  1.005  4.0  0.0    1   0    1   0  ...  32.0  6700.0   
4      4  51.0  80.0  1.010  2.0  0.0    1   1    0   0  ...  35.0  7300.0   
..   ...   ...   ...    ...  ...  ...  ...  ..  ...  ..  ...   ...     ...   
395  395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  ...  47.0  6700.0   
396  396  42.0  70.0  1.025  0.0  0.0    1   1    0   0  ...  54.0  7800.0   
397  397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  ...  49.0  6600.0   
398  398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  ...  51.0  7200.0   
399  399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  ...  53.0  6800.0   

           rc  htn  dm  cad  appet   pe  ane  classification  
0    5.200000    1   1   no   good   no   no             ckd  
1    4.707435    0   0   no   good   no   no             ckd  
2    4.707435    0   1   no   poor   no  yes             ckd  
3    3.900000    1   0   no   poor  yes  yes             ckd  
4    4.600000    0   0   no   good   no   no             ckd  
..        ...  ...  ..  ...    ...  ...  ...             ...  
395  4.900000    0   0   no   good   no   no          notckd  
396  6.200000    0   0   no   good   no   no          notckd  
397  5.400000    0   0   no   good   no   no          notckd  
398  5.900000    0   0   no   good   no   no          notckd  
399  6.100000    0   0   no   good   no   no          notckd  

[400 rows x 26 columns]

In [30]:
df['cad'].isna().sum()
#cleaning the noise in the data
df['cad'].replace('\tno', 'no',inplace = True)

#discrete values so we replaced with most frequent
cad_frequent_value = df['cad'].value_counts().idxmax()
df['cad'].replace(np.nan, cad_frequent_value, inplace = True )

#encoding and processing the values
df['cad'].replace('no', 0, inplace = True)
df['cad'].replace('yes', 1, inplace = True)

df['cad'].unique()

array([0, 1], dtype=int64)

In [31]:
df['appet'].isna().sum()
#one row has null values so we'll just drop it  
df.dropna(subset = ['appet'], axis =0, inplace = True)

#encoding and processing the values
df['appet'].replace('poor', 0, inplace = True)
df['appet'].replace('good', 1, inplace = True)

df['appet'].unique()

array([1, 0], dtype=int64)

In [32]:
df['pe'].isna().sum()
#one row has null values so we'll just drop it  
df.dropna(subset = ['pe'], axis =0, inplace = True)

#encoding and processing the values
df['pe'].replace('no', 0, inplace = True)
df['pe'].replace('yes', 1, inplace = True)

df['pe'].unique()

array([0, 1], dtype=int64)

In [33]:
df['ane'].isna().sum()
#one row has null values so we'll just drop it  
df.dropna(subset = ['ane'], axis =0, inplace = True)

#encoding and processing the values
df['ane'].replace('no', 0, inplace = True)
df['ane'].replace('yes', 1, inplace = True)

df['ane'].unique()

array([0, 1], dtype=int64)

In [34]:
df['classification'].unique()
df['classification'].replace('notckd', 0, inplace = True)
df['classification'].replace('ckd', 1, inplace = True)
df['classification'].replace('ckd\t', 2, inplace = True)
df['classification'].replace(2, 1, inplace = True)


In [35]:
df.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                False
rbc               False
pc                False
pcc               False
ba                False
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [36]:
df.to_csv('C:/Users/Pro/Desktop/kidney0.csv')

# here is the correlation between our target column and the rest of the columns in the dataset

In [37]:
df['classification'].corr(df['age'])

0.2309325672171259

In [38]:
df['classification'].corr(df['bp'])

0.2877819301904025

In [39]:
df['classification'].corr(df['sg'])

-0.6596662096317505

In [40]:
df['classification'].corr(df['al'])

0.5307639393511075

In [41]:
df['classification'].corr(df['su'])

0.29399286776969685

In [42]:
df['classification'].corr(df['rbc'])

-0.28209846765720925

In [43]:
df['classification'].corr(df['pc'])

-0.37448003166744026

In [44]:
df['classification'].corr(df['pcc'])

0.26479736981100005

In [45]:
df['classification'].corr(df['ba'])

0.18649354103776986

In [46]:
df['classification'].corr(df['bgr'])

0.40069347068301214

In [47]:
df['classification'].corr(df['bu'])

0.37233379778307607

In [48]:
df['classification'].corr(df['sc'])

0.2933901033985219

In [49]:
df['classification'].corr(df['sod'])

-0.34392947480106295

In [50]:
df['classification'].corr(df['pot'])

0.07751348454561326

In [51]:
df['classification'].corr(df['hemo'])

-0.7294281589557993

In [52]:
df['classification'].corr(df['pcv'])

-0.6910779367700747

In [53]:
df['classification'].corr(df['rc'])

-0.5891830887526028

In [54]:
df['classification'].corr(df['wc'])

0.20556818961386122

In [55]:
df['classification'].corr(df['htn'])

0.5896326540030383

In [56]:
df['classification'].corr(df['dm'])

0.5582551880294817

In [57]:
df['classification'].corr(df['cad'])

0.23562217259667675

In [58]:
df['classification'].corr(df['appet'])

-0.39264531959919574

In [59]:
df['classification'].corr(df['pe'])

0.37448003166744026

In [60]:
df['classification'].corr(df['ane'])

0.32478720058480876

In [44]:
#df.dropna(subset=['id'], axis = 1, inplace = True)


In [90]:
df

age    bp     sg   al   su  rbc  pc  pcc  ba         bgr  ...   pcv  \
0    48.0  80.0  1.020  1.0  0.0    1   1    0   0  121.000000  ...  44.0   
1     7.0  50.0  1.020  4.0  0.0    1   1    0   0  148.036517  ...  38.0   
2    62.0  80.0  1.010  2.0  3.0    1   1    0   0  423.000000  ...  31.0   
3    48.0  70.0  1.005  4.0  0.0    1   0    1   0  117.000000  ...  32.0   
4    51.0  80.0  1.010  2.0  0.0    1   1    0   0  106.000000  ...  35.0   
..    ...   ...    ...  ...  ...  ...  ..  ...  ..         ...  ...   ...   
395  55.0  80.0  1.020  0.0  0.0    1   1    0   0  140.000000  ...  47.0   
396  42.0  70.0  1.025  0.0  0.0    1   1    0   0   75.000000  ...  54.0   
397  12.0  80.0  1.020  0.0  0.0    1   1    0   0  100.000000  ...  49.0   
398  17.0  60.0  1.025  0.0  0.0    1   1    0   0  114.000000  ...  51.0   
399  58.0  80.0  1.025  0.0  0.0    1   1    0   0  131.000000  ...  53.0   

         wc        rc  htn  dm  cad  appet  pe  ane  classification  
0    7800.0  5.200000    1   1    0      1   0    0               1  
1    6000.0  4.707435    0   0    0      1   0    0               1  
2    7500.0  4.707435    0   1    0      0   0    1               1  
3    6700.0  3.900000    1   0    0      0   1    1               1  
4    7300.0  4.600000    0   0    0      1   0    0               1  
..      ...       ...  ...  ..  ...    ...  ..  ...             ...  
395  6700.0  4.900000    0   0    0      1   0    0               0  
396  7800.0  6.200000    0   0    0      1   0    0               0  
397  6600.0  5.400000    0   0    0      1   0    0               0  
398  7200.0  5.900000    0   0    0      1   0    0               0  
399  6800.0  6.100000    0   0    0      1   0    0               0  

[399 rows x 25 columns]

In [ ]:
df.to_csv('C:/Users/Pro/Desktop/kidney0.csv')

In [37]:
import pandas as pd 
import numpy as np 

In [40]:
df = pd.read_csv('C:/Users/Pro/Desktop/kidney0.csv')

In [16]:
df.dtypes

age               float64
bp                float64
sg                float64
al                float64
su                float64
rbc                 int64
pc                  int64
pcc                 int64
ba                  int64
bgr               float64
bu                float64
sc                float64
sod               float64
pot               float64
hemo              float64
pcv               float64
wc                float64
rc                float64
htn                 int64
dm                  int64
cad                 int64
appet               int64
pe                  int64
ane                 int64
classification      int64
dtype: object

In [17]:
df.astype(float)

age    bp     sg   al   su  rbc   pc  pcc   ba         bgr  ...   pcv  \
0    48.0  80.0  1.020  1.0  0.0  1.0  1.0  0.0  0.0  121.000000  ...  44.0   
1     7.0  50.0  1.020  4.0  0.0  1.0  1.0  0.0  0.0  148.036517  ...  38.0   
2    62.0  80.0  1.010  2.0  3.0  1.0  1.0  0.0  0.0  423.000000  ...  31.0   
3    48.0  70.0  1.005  4.0  0.0  1.0  0.0  1.0  0.0  117.000000  ...  32.0   
4    51.0  80.0  1.010  2.0  0.0  1.0  1.0  0.0  0.0  106.000000  ...  35.0   
..    ...   ...    ...  ...  ...  ...  ...  ...  ...         ...  ...   ...   
394  55.0  80.0  1.020  0.0  0.0  1.0  1.0  0.0  0.0  140.000000  ...  47.0   
395  42.0  70.0  1.025  0.0  0.0  1.0  1.0  0.0  0.0   75.000000  ...  54.0   
396  12.0  80.0  1.020  0.0  0.0  1.0  1.0  0.0  0.0  100.000000  ...  49.0   
397  17.0  60.0  1.025  0.0  0.0  1.0  1.0  0.0  0.0  114.000000  ...  51.0   
398  58.0  80.0  1.025  0.0  0.0  1.0  1.0  0.0  0.0  131.000000  ...  53.0   

         wc        rc  htn   dm  cad  appet   pe  ane  classification  
0    7800.0  5.200000  1.0  1.0  0.0    1.0  0.0  0.0             1.0  
1    6000.0  4.707435  0.0  0.0  0.0    1.0  0.0  0.0             1.0  
2    7500.0  4.707435  0.0  1.0  0.0    0.0  0.0  1.0             1.0  
3    6700.0  3.900000  1.0  0.0  0.0    0.0  1.0  1.0             1.0  
4    7300.0  4.600000  0.0  0.0  0.0    1.0  0.0  0.0             1.0  
..      ...       ...  ...  ...  ...    ...  ...  ...             ...  
394  6700.0  4.900000  0.0  0.0  0.0    1.0  0.0  0.0             0.0  
395  7800.0  6.200000  0.0  0.0  0.0    1.0  0.0  0.0             0.0  
396  6600.0  5.400000  0.0  0.0  0.0    1.0  0.0  0.0             0.0  
397  7200.0  5.900000  0.0  0.0  0.0    1.0  0.0  0.0             0.0  
398  6800.0  6.100000  0.0  0.0  0.0    1.0  0.0  0.0             0.0  

[399 rows x 25 columns]

In [20]:
#seperating input from output
output = df['classification']
inputt = df.drop('classification', axis = 1 )

In [21]:
from sklearn.model_selection import train_test_split 

In [22]:
x_train, x_test, y_train, y_test =  train_test_split(inputt,output, test_size = 0.3, random_state = 1)

In [23]:
x_train.shape

(279, 25)

In [24]:
x_test.shape

(120, 25)

# using KNN Algorthim

In [80]:
from sklearn.neighbors import KNeighborsClassifier 

In [81]:
#using KNN to train the model 
#training the model 
KNN_model = KNeighborsClassifier()
KNN_model.fit(x_train, y_train)
#testing the model 
y_predict = KNN_model.predict(x_test)
y_predict

array([0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1], dtype=int64)

In [82]:
from sklearn.metrics import accuracy_score, confusion_matrix 
from sklearn.metrics import f1_score , precision_score

In [83]:
print("Model Accuracy", accuracy_score(y_test,y_predict))
print("Model precision ", precision_score(y_test,y_predict))
print("Model F1 Score", f1_score(y_test,y_predict))
print("Confusion matrix is  \n" , confusion_matrix(y_test,y_predict))


Model Accuracy 0.9
Model precision  0.927536231884058
Model F1 Score 0.9142857142857144
Confusion matrix is  
 [[44  5]
 [ 7 64]]


# using XGboost Algorithm

In [25]:
from sklearn.metrics import accuracy_score, confusion_matrix 
from sklearn.metrics import f1_score , precision_score

In [26]:
import xgboost as xgb
from  xgboost import XGBClassifier

In [27]:
XG_model =XGBClassifier()
XG_model.fit(x_train,y_train)
y_predict=XG_model.predict(x_test)
y_predict

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1])

In [28]:
print("Model Accuracy", accuracy_score(y_test,y_predict))
print("Model precision ", precision_score(y_test,y_predict))
print("Model F1 Score", f1_score(y_test,y_predict))
print("Confusion matrix is  \n" , confusion_matrix(y_test,y_predict))


Model Accuracy 1.0
Model precision  1.0
Model F1 Score 1.0
Confusion matrix is  
 [[49  0]
 [ 0 71]]


# using SVM Algorithm

In [88]:
from sklearn.metrics import accuracy_score, confusion_matrix 
from sklearn.metrics import f1_score , precision_score

In [89]:
from sklearn import svm
from sklearn.svm import SVC

In [90]:
SVM_model = SVC()
SVM_model.fit(x_train, y_train)
y_predict = SVM_model.predict(x_test)

In [91]:
print("Model Accuracy", accuracy_score(y_test,y_predict))
print("Model precision ", precision_score(y_test,y_predict))
print("Model F1 Score", f1_score(y_test,y_predict))
print("Confusion matrix is  \n" , confusion_matrix(y_test,y_predict))


Model Accuracy 0.5916666666666667
Model precision  0.5916666666666667
Model F1 Score 0.743455497382199
Confusion matrix is  
 [[ 0 49]
 [ 0 71]]


# using Random Forest Algorithm

In [92]:
from sklearn.metrics import accuracy_score, confusion_matrix 
from sklearn.metrics import f1_score , precision_score

In [93]:
from sklearn.ensemble import RandomForestClassifier

In [94]:
RF_model = RandomForestClassifier(n_estimators=1000,criterion="entropy",random_state=1)
RF_model.fit(x_train,y_train)
y_predict = RF_model.predict(x_test)
y_predict

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1], dtype=int64)

In [95]:
print("Model Accuracy", accuracy_score(y_test,y_predict))
print("Model precision ", precision_score(y_test,y_predict))
print("Model F1 Score", f1_score(y_test,y_predict))
print("Confusion matrix is  \n" , confusion_matrix(y_test,y_predict))


Model Accuracy 1.0
Model precision  1.0
Model F1 Score 1.0
Confusion matrix is  
 [[49  0]
 [ 0 71]]


# using Decision Tree Alogrithm

In [96]:
from sklearn.metrics import accuracy_score, confusion_matrix 
from sklearn.metrics import f1_score , precision_score

In [97]:
from sklearn.tree import DecisionTreeClassifier

In [98]:
DT_model=DecisionTreeClassifier(criterion='gini' , splitter='best' , max_depth=None)
DT_model.fit(x_train,y_train)
y_predict=DT_model.predict(x_test)
y_predict

array([1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 0, 1], dtype=int64)

In [99]:
print("Model Accuracy", accuracy_score(y_test,y_predict))
print("Model precision ", precision_score(y_test,y_predict))
print("Model F1 Score", f1_score(y_test,y_predict))
print("Confusion matrix is  \n" , confusion_matrix(y_test,y_predict))


Model Accuracy 1.0
Model precision  1.0
Model F1 Score 1.0
Confusion matrix is  
 [[49  0]
 [ 0 71]]


In [29]:
import joblib as jb

In [30]:
jb.dump(XG_model,'C:/Users/Pro/Desktop/kmodel.sav')

['C:/Users/Pro/Desktop/kmodel.sav']

In [104]:
jb.dump(DT_model, 'C:/Users/Pro/Desktop/kmodel0.sav')

['C:/Users/Pro/Desktop/kmodel0.sav']